kind: Secret
apiVersion: v1
metadata:
  name: {{ template "nbviewer.fullname" . }}
  labels:
    {{- include "nbviewer.labels" . | nindent 4 }}
type: Opaque
data:
  github-accessToken: {{ .Values.github.accessToken | b64enc | quote }}
  github-clientId: {{ .Values.github.clientId | b64enc | quote }}
  github-clientSecret: {{ .Values.github.clientSecret | b64enc | quote }}
  statuspage-apiKey: {{ .Values.statuspage.apiKey | b64enc | quote }}
  newrelic-ini: {{ .Values.nbviewer.newrelicIni | b64enc | quote }}
